#!/bin/bash

# -2 color; new-seesion one new window; split-window, h vertical, v horizontal; select-pane -t panel number; split 3 and vertically even
tmux -2 new-session \; send-keys C-c \; split-window -v \;
